### ISSUE TITLE
Patch the image

### ISSUE THREAD

**Issue by nooralahzadeh** [gupta-abhay/ViT#1]
How do you patch the image?  any clues for the preprocessing and training step?

**Comment by gupta-abhay** [comment]
Working on this now. Should have some code over the next few days.

**Comment by nooralahzadeh** [comment]
`from einops import rearrange`
`p = self.patch_size`
`x = rearrange(img, 'b c (h p1) (w p2) -> b (h w) (p1 p2 c)', p1 = p, p2 = p)`
