### ISSUE TITLE
Why only use the first patch? Thanks

### ISSUE THREAD

**Issue by junyongyou** [gupta-abhay/ViT#5]
I don't understand the line 74 of ViT.py:
`x = self.to_cls_token(x[:, 0])`
If the first dimension of x is batch, then the 2nd dimension 0 should be patch, as the dimension of x should be [batch, patch, feature]. Does it mean only the first patch is used? Could anybody help me on this? Thanks a lot.

**Comment by gupta-abhay** [comment]
Hi,

We use this for the classification. If you refer the paper, in equation 4 where they describe the model layout -- they take only layer norm of z_0 -- which is the first token. and that's why I extract that out.

**Comment by junyongyou** [comment]
> 
> 
> Hi,
> 
> We use this for the classification. If you refer the paper, in equation 4 where they describe the model layout -- they take only layer norm of z_0 -- which is the first token. and that's why I extract that out.

Yes. I have already read carefully the BERT paper, and understood it now. Thanks a lot.
