### ISSUE TITLE
layout for vit: NCHW or NHWC? bugpropagation

### ISSUE THREAD

**Issue by etienne87** [gupta-abhay/ViT#7]
hello, 
Thanks a lot for this very interesting work!

when you unroll the tensor you use unfold and flatten like this:

```
x = (x.unfold(2, self.patch_dim, self.patch_dim).
unfold(3, self.patch_dim, self.patch_dim).contiguous())
x = x.view(x.size(0), -1, self.flatten_dim)
```

but if x is in shape N,C,H,W, unrolling ends up with N,C,H//P,W//P,P,P and therefore flattening ends up mixing data from different channels. It means your "words" come from different blocks in space. It does not really matter for training your model with one specific size, but i think it will have hard time to transfer to a different size...

instead you could do like this:
```
self.flatten_dim_in = (patch_dim**2) * in_channels
...
x = (x.unfold(2, self.patch_dim, self.patch_dim)
         .unfold(3, self.patch_dim, self.patch_dim) .contiguous())
x = x.view(b,c,-1,self.patch_dim**2)
x = x.permute(0,2,3,1).contiguous()
x = x.view(x.size(0), -1, self.flatten_dim_in)
```
Just to make sure the data at the end is really what you expect: all the rgb pixels of one patch together, and not a mix of patches together.

Now i haven't tried your code yet so perhaps you have a different layout than N,C,H,W  for images?

**Comment by gupta-abhay** [comment]
good catch. thanks for this :)

**Comment by etienne87** [comment]
you are welcome :) thanks for this work

**Comment by etienne87** [comment]
btw you can do like this as well: x = rearrange(img, 'b c (h p1) (w p2) -> b (h w) (p1 p2 c)', p1 = p, p2 = p)
